// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF7fsleQw4FmiBLZQ6JhlQ2lnuQQJnrjk',
    appId: '1:241665118590:web:0950a79a11c6d02825632f',
    messagingSenderId: '241665118590',
    projectId: 'trouble-sarthi',
    authDomain: 'trouble-sarthi.firebaseapp.com',
    storageBucket: 'trouble-sarthi.firebasestorage.app',
    measurementId: 'G-PZCZ7BJEZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH4Xi0xrqWZKQLkxv80rkSBpnVI-AJYvI',
    appId: '1:241665118590:android:a764c51389038d0025632f',
    messagingSenderId: '241665118590',
    projectId: 'trouble-sarthi',
    storageBucket: 'trouble-sarthi.firebasestorage.app',
    databaseURL: 'https://trouble-sarthi-default-rtdb.firebaseio.com', // ← ADDED
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN_OXztXdybB0c7J8tY7-Pdl-fNUm9YwQ',
    appId: '1:241665118590:ios:8c60d911e0e3601a25632f',
    messagingSenderId: '241665118590',
    projectId: 'trouble-sarthi',
    storageBucket: 'trouble-sarthi.firebasestorage.app',
    iosBundleId: 'com.example.troubleSarthi',
    databaseURL: 'https://trouble-sarthi-default-rtdb.firebaseio.com', // ← ADDED
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN_OXztXdybB0c7J8tY7-Pdl-fNUm9YwQ',
    appId: '1:241665118590:ios:8c60d911e0e3601a25632f',
    messagingSenderId: '241665118590',
    projectId: 'trouble-sarthi',
    storageBucket: 'trouble-sarthi.firebasestorage.app',
    iosBundleId: 'com.example.troubleSarthi',
    databaseURL: 'https://trouble-sarthi-default-rtdb.firebaseio.com', // ← ADDED
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTyz4ZSHFKtg9Eq-eZ2rD5fPcapNRyQyo',
    appId: '1:241665118590:web:595fe369eed7da3725632f',
    messagingSenderId: '241665118590',
    projectId: 'trouble-sarthi',
    authDomain: 'trouble-sarthi.firebaseapp.com',
    storageBucket: 'trouble-sarthi.firebasestorage.app',
    measurementId: 'G-HH6V68KFY0',
  );
}
